sudo: required
language: generic
services: 
  - docker
  
before_install:
  - docker build -t manicsaran/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true manicsaran/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-135821823334"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
