sudo: required
language: generic
services: 
  - docker
  
before_install:
  - docker build -t manicsaran/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true msaravan/docker-react npm run test 
