sudo: required
language: generic
services: 
  - docker
  
before_install:
  - docker build -t manicsaran/docker-react -f Dockerfile.dev .

script:
  - docker run manicsaran/docker-react npm run test -- --coverage
